spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/${DB_NAME:gmuwiki}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Esperer123!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
server:
  port: ${SERVER_PORT:8080}
